# core/configs/scaler_rag/scaler03_dim_reduction.yaml

# Compare the performance of dimensionality reduction for RAG.

# IntraDocumentQA & no dimensionality reduction & Kmean
scaler_rag_03_01:
  dataset:
    name: qasper
    number_of_docs: 200
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

# InterDocumentQA & no dimensionality reduction & Kmean
scaler_rag_03_02:
  dataset:
    name: frames
    number_of_qas: 400
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

# IntraDocumentQA & no dimensionality reduction & GMM
scaler_rag_03_03:
  dataset:
    name: qasper
    number_of_docs: 200
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

# InterDocumentQA & no dimensionality reduction & GMM
scaler_rag_03_04:
  dataset:
    name: frames
    number_of_qas: 400
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1
