# core/configs/scaler_rag/scaler02_gmm.yaml

# Compare the performance of different LLMs for RAG.
# - whether the gmm is better than the normal model
# - whether the gmm is better than the kmean
#
# Tested on IntraDocumentQA (Qasper) and InterDocumentQA (Frames).

# GMM
#  IntraDocumentQA (Qasper) & GMM
scaler_rag_02_01:
  dataset:
    name: qasper
    number_of_docs: 200
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "gmm"
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

# InterDocumentQA (Frames) & GMM
scaler_rag_02_02:
  dataset:
    name: frames
    number_of_qas: 400
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "gmm"
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

# # IntraDocumentQA (Qasper) & Kmean 
# #  Same as scaler_rag_01_02
# scaler_rag_02_03:
#   dataset:
#     name: qasper
#     number_of_docs: 200
#   chunker:
#     mode: sentence
#     size: 100
#     overlap: 0.2
#     embedding_id: huggingface-multi-qa-mpnet
#     clustering:
#       method: "kmeans"
#     dim_reduction:
#       method: "pca"
#       n_components: 15
#   retrieval_generation:
#     faiss_search: "flatl2"
#     top_k: 5
#     llm_id: llama3.1

# # InterDocumentQA & Sentence Chunking
# #  Same as scaler_rag_01_04
# scaler_rag_02_04:
#   dataset:
#     name: frames
#     number_of_qas: 400
#   chunker:
#     mode: sentence
#     size: 100
#     overlap: 0.2
#     embedding_id: huggingface-multi-qa-mpnet
#     clustering:
#       method: "kmeans"
#     dim_reduction:
#       method: "pca"
#       n_components: 15
#   retrieval_generation:
#     faiss_search: "flatl2"
#     top_k: 10
#     llm_id: llama3.1