# core/configs/scaler_rag/scaler01_sentence_chunk.yaml

""" 
Compare the performance of sentence chunking for RAG.
- whether the sentence chunking is better than the fixed chunking

Tested for both IntraDocumentQA (Qasper) and InterDocumentQA (Frames).
"""

# IntraDocumentQA & Fixed Chunking
scaler_rag_01_01:
  dataset: 
    name: qasper
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "kmeans"
      items_per_cluster: 15
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

# IntraDocumentQA & Sentence Chunking
scaler_rag_01_02:
  dataset:
    name: qasper
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "kmeans"
      items_per_cluster: 15
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

# InterDocumentQA & Fixed Chunking
scaler_rag_01_03:
  dataset:
    name: frames
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "kmeans"
      items_per_cluster: 15
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

# InterDocumentQA & Sentence Chunking
scaler_rag_01_04:
  dataset:
    name: frames
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: "kmeans"
      items_per_cluster: 15
    dim_reduction:
      method: "pca"
      n_components: 15
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1