# core/configs/scaler_rag/scaler03_dim_reduction.yaml

# Compare the performance of dimensionality reduction for RAG.

# IntraDocumentQA (Qasper) & no dimensionality reduction & Kmean
scaler_rag_03_01:
  dataset:
    name: qasper
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# IntraDocumentQA(Qasper) & no dimensionality reduction & GMM
scaler_rag_03_02:
  dataset:
    name: qasper
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA(Frames) & no dimensionality reduction & Kmean
scaler_rag_03_03:
  dataset:
    name: frames
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 256
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA(Frames) & no dimensionality reduction & GMM
scaler_rag_03_04:
  dataset:
    name: frames
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 256
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# IntraDocumentQA(NarrativeQA) & no dimensionality reduction & Kmean
scaler_rag_03_05:
  dataset:
    name: narrativeqa
    number_of_docs: 100
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# IntraDocumentQA(NarrativeQA) & no dimensionality reduction & GMM
scaler_rag_03_06:
  dataset:
    name: narrativeqa
    number_of_docs: 100
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA & no dimensionality reduction & Kmean
scaler_rag_03_07:
  dataset:
    name: multihoprag
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 256
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: kmeans
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA(MultiHopRAG) & no dimensionality reduction & GMM
scaler_rag_03_08:
  dataset:
    name: multihoprag
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 256
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
    clustering:
      method: gmm
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b