# core/configs/rag_sentence_chunk.yaml

# Compare the performance of sentence chunking for RAG.
# - whether the sentence chunking is better than the fixed chunking
#
# Tested for both IntraDocumentQA (Qasper) and InterDocumentQA (Frames).

# IntraDocumentQA & Fixed Chunking
simple_rag_01_01:
  dataset: 
    name: qasper
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# IntraDocumentQA & Sentence Chunking
simple_rag_01_02:
  dataset:
    name: qasper
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA & Fixed Chunking
simple_rag_01_03:
  dataset:
    name: frames
    number_of_qas: 500
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA & Sentence Chunking
simple_rag_01_04:
  dataset:
    name: frames
    number_of_qas: 500
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# IntraDocumentQA(NarrativeQA) & Sentence Chunking
simple_rag_01_05:
  dataset:
    name: narrativeqa
    number_of_docs: 100
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: gemini-1.5-flash-8b

# InterDocumentQA(MultiHopRAG) & Sentence Chunking
simple_rag_01_06:
  dataset:
    name: multihoprag
    number_of_qas: 500
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b