# Experiment test
TEST02_simple_rag_01:
  dataset: 
    name: qasper
    number_of_docs: 30
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

TEST02_simple_rag_02:
  dataset:
    name: multihoprag
    number_of_qas: 50
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

TEST02_simple_rag_03:
  dataset:
    name: narrativeqa
    number_of_docs: 10
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

TEST02_simple_rag_04:
  dataset:
    name: frames
    number_of_qas: 50
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1



# Simple RAG test
TEST_simple_rag_qasper:
  dataset: 
    name: qasper
    number_of_docs: 3
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1

TEST_simple_rag_multihoprag:
  dataset:
    name: multihoprag
    number_of_qas: 15
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1