# core/configs/scaler_v1_rag/comparison.yaml

# vs scaler_rag_01_03 at scaler_rag/scaler01_sentence_chunk.yaml
scaler_v1_rag_01_01:
  dataset:
    name: frames
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 512
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

# vs scaler_rag_01_04 at scaler_rag/scaler01_sentence_chunk.yaml
scaler_v1_rag_01_02:
  dataset:
    name: multihoprag
    number_of_qas: 500
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 512
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: sentence
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: gemini-1.5-flash-8b

