# core/configs/scaler_v1_rag/test.yaml

# Experiment test
TEST02_scaler_v1_rag_02:
  dataset:
    name: multihoprag
    number_of_qas: 100
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1

TEST02_scaler_v1_rag_04:
  dataset:
    name: frames
    number_of_qas: 50
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 10
    llm_id: llama3.1



# Simple RAG test
TEST_scaler_v1_rag_multihoprag:
  dataset:
    name: multihoprag
    number_of_qas: 5
    selection_mode: sequential
  summarizer:
    llm_id: llama3.2:1b
    output_tokens: 512
    embedding_id: huggingface-multi-qa-mpnet
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
    embedding_id: huggingface-multi-qa-mpnet
  retrieval_generation:
    faiss_search: "flatl2"
    top_k: 5
    llm_id: llama3.1