
# Simple RAG test
simple_rag_qasper_test:
  dataset: 
    name: qasper
    number_of_docs: 1
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
  model:
    llm_id: llama3.1
    embedding_id: huggingface-multi-qa-mpnet
  retrieval:
    faiss_search: "flatl2"
    top_k: 5