
# Simple RAG test
simple_rag_qasper_test:
  dataset: 
    name: qasper
    number_of_docs: 5
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
  model:
    llm_id: llama3.1
    embedding_id: huggingface-multi-qa-mpnet
  retrieval:
    faiss_search: "flatl2"
    top_k: 5

simple_rag_multihoprag_test:
  dataset:
    name: multihoprag
    number_of_qas: 50
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
  model:
    llm_id: llama3.1
    embedding_id: huggingface-multi-qa-mpnet
  retrieval:
    faiss_search: "flatl2"
    top_k: 5

simple_rag_narrativeqa_test:
  dataset:
    name: narrativeqa
    number_of_docs: 3
    selection_mode: sequential    
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
  model:
    llm_id: llama3.1
    embedding_id: huggingface-multi-qa-mpnet
  retrieval:
    faiss_search: "flatl2"
    top_k: 5

simple_rag_frames_test:
  dataset:
    name: frames
    number_of_qas: 20
    selection_mode: sequential
  chunker:
    mode: fixed
    size: 100
    overlap: 0.2
  model:
    llm_id: llama3.1
    embedding_id: huggingface-multi-qa-mpnet
  retrieval:
    faiss_search: "flatl2"
    top_k: 5
